name: ioanatodosia
favicon: null
layout_spectrum: 0.31836254079826176
typography_spectrum: 0.5537952822633088
title: Ioana Todosia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.4428503718227148
  lightness: 0.1802551916334778
  saturation: 0.8696574359200895
  rhythmicContrast: 0.05808732379227877
purpose: []
