name: ioanatodosia
favicon: null
layout_spectrum: 0.269
typography_spectrum: 0.5537952822633088
title: Ioana Todosia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#84a9cb'
    - '#060709'
    - '#3d3737'
    - '#f8e0b7'
    - '#b92f33'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 0
purpose: []
